name: good morning action
on: workflow_dispatch

jobs:
  say-good-morning:
    runs-on: ubuntu-latest
    steps:
      - name: say-good-morning
        id: good-morning
        uses: Roboshop-2/workflows/.github/actions/gm@main
        with:
          person: "Ramesh"


      - name: get the output
        run: |
          echo "${{ steps.good-morning.outputs.greeting-status }}"